// <auto-generated />
namespace IBuyServer.Domain.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingpricecolumnandatableforexpenses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingpricecolumnandatableforexpenses));
        
        string IMigrationMetadata.Id
        {
            get { return "201902141139465_adding price column and a table for expenses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
